### ISSUE TITLE
Namelist parser bug

### ISSUE THREAD

**Issue by logan-nc** [gafusion/harvest_client#2]
Just tried sending the IPEC input namelists and get this error when trying to read it in OMFIT. I think it might be an error in the harvest server namelist parser, which is why I am putting it as an issue here instead of OMFIT. Let me know if otherwise.

Error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/task/imd/anaconda/lib/python2.7/lib-tk/Tkinter.py", line 1536, in **call**
    return self.func(*args)
  File "/usc-data/task/imd/OMFIT-tmp/src/OMFITgui.py", line 1439, in update_treeGUI
    self.commandNamespace()
  File "/usc-data/task/imd/OMFIT-tmp/src/OMFITgui.py", line 1483, in commandNamespace
    self._update_treeGUI()
  File "/usc-data/task/imd/OMFIT-tmp/src/OMFITgui.py", line 1630, in _update_treeGUI
    insert_traverse(OMFIT,'')
  File "/usc-data/task/imd/OMFIT-tmp/src/OMFITgui.py", line 1577, in insert_traverse
    insert_traverse(meKid,entryID)
  File "/usc-data/task/imd/OMFIT-tmp/src/OMFITgui.py", line 1577, in insert_traverse
    insert_traverse(meKid,entryID)
  File "/usc-data/task/imd/OMFIT-tmp/src/OMFITgui.py", line 1577, in insert_traverse
    insert_traverse(meKid,entryID)
  File "/usc-data/task/imd/OMFIT-tmp/src/OMFITgui.py", line 1577, in insert_traverse
    insert_traverse(meKid,entryID)
  File "/usc-data/task/imd/OMFIT-tmp/src/OMFITgui.py", line 1539, in insert_traverse
    meKeys=sorted(sorted(meKeys),key=sortHuman)
  File "/usc-data/task/imd/OMFIT-tmp/src/sortedDict.py", line 41, in sortHuman
    outStr=re.subn('\1',format(float(kn),"+040.16f"),outStr,1)[0]
ValueError: invalid literal for float(): 2e

**Comment by orso82** [comment]
I **just** pushed the fix in OMFIT. Please try it there and let me know if it works.

**Comment by logan-nc** [comment]
My omfit-tmp HARVEST timestamps are still from march...

![image](https://cloud.githubusercontent.com/assets/6198372/9065872/22c579a8-3a89-11e5-9971-0715efd4fcad.png)

**Comment by orso82** [comment]
It's a european styled date :)
03 Aug 2015

**Comment by smithsp** [comment]
Also, the fix was to the underlying `Namelist` class, not the HARVEST module.

**Comment by logan-nc** [comment]
Closed and re-opened. Same error... try opening CODEDB_IPEC package 2 or 3. Can you do it?

**Comment by smithsp** [comment]
Is this still an issue?

**Comment by logan-nc** [comment]
I don't even see the harvest module in OMFIT anymore! What did I miss?

**Comment by orso82** [comment]
The HARVEST module is gone, in favor of the `OMFITharvestS3` class.
